import { FrasesHModel } from './frasesh.model';
import { FrasesPModel } from './frasesp.model';
import { PeligrosidadNTCModel } from './peligrosidadNTC.model';
import { ProductoModel } from './producto.model';
import { SgaAmbientalModel } from './sgaambiental.model';
import { SgaFisicoModel } from './sgafisico.model';
import { SgaSaludModel } from './sgasalud.model';

export class RiesgoQuimicoModel {
    idRiesgo: number;
    idProductoFk: ProductoModel;
    gre: number;
    numeroUn: string;
    cas: string;
    cancerigeno: string;
    categoriaIARC: string;
    categoriaACGIH: string;
    nfpaS: number;
    nfpaI: number;
    nfpaR: number;
    nfpaE: string;
    idSGAAmbientalFk: SgaAmbientalModel;
    reactividad: string;
    estabilidadQuimica: string;
    reaccionesPeligrosas: string;
    sustanciasIncompatibles: string;
    twa: string;
    stell: string;
    tlvC: string;
    peligroInhalacion: string;
    peligroIngestion: string;
    peligroPiel: string;
    peligroOjos: string;
    efectosCronicos: string;
    medidasRespiratorias: string;
    medidasManos: string;
    medidasOjos: string;
    medidasPiel: string;
    medidasHigiene: string;
    medidasControlIng: string;
    medidasAlmacenamiento: string;
    medidasManipulacion: string;
    prAuxInhalacion: string;
    prAuxIngestion: string;
    prAuxPiel: string;
    prAuxOjos: string;
    prAuxOtras: string;
    peligroEspIncendio: string;
    peligroEspSalud: string;
    recomendacionIncendio: string;
    agenteExtintor: string;
    ctrolProctecFuga: string;
    ctrolLimpieza: string;
    fichaSeguridad: string;
    tarjetaEmergencia: string;
    palabraEmergencia: string;
    imagen: string;
    constructor() {
        this.idProductoFk = new ProductoModel;
        this.idSGAAmbientalFk = new SgaAmbientalModel;
        this.gre = 157;
        this.numeroUn = "7697 - 37 - 2";
        this.cas = "1818";
        this.cancerigeno = "NO";
        this.categoriaIARC = "1";
        this.categoriaACGIH = "A1";
        this.nfpaS = 3;
        this.nfpaI = 1;
        this.nfpaR = 1;
        this.nfpaE = "oxidante(OX)";
        this.idSGAAmbientalFk.id = 3;
        this.reactividad = "Oxidante energetico";
        this.estabilidadQuimica = "Riesgo de explosion con=Acetona, Alcoholes, Nitrocompuestos, Manganeso, Cianuros,Peligro Ignicion=Amoniaco, Aldehidos, Potasio.Posibles reacciones violentas=Nitrilos, antimonio, arsenico, hierro Oxido";
        this.reaccionesPeligrosas = "Gases nitrosos Oxidos de nitrogeno";
        this.sustanciasIncompatibles = "Celulosa,Metales";
        this.twa = "twa";
        this.stell = "stell";
        this.tlvC = "tlvC";
        this.peligroInhalacion = "Toxicidad aguda por inhalacion Sintomas=quemaduras en las mucosas, tos, insuficiencia respiratoria";
        this.peligroIngestion = "Toxicidad oral aguda Sintomas=quemaduras severas de la boca y garganta, peligro de perforacion del esófago y del estómago.";
        this.peligroPiel = "Provoca quemaduras graves";
        this.peligroOjos = "Provoca quemaduras graves";
        this.efectosCronicos = "";
        this.medidasRespiratorias = "Respirador con filtro para gases acidos ";
        this.medidasManos = "Guantes de Nitrilo";
        this.medidasOjos = "Gafas de seguridad";
        this.medidasPiel = "Bata de laboratorio";
        this.medidasHigiene = "Lavado de manos antes y despues de la manipulacion";
        this.medidasControlIng = "Campana de extracciòn";
        this.medidasAlmacenamiento = "No usar recipientes metalicos";
        this.medidasManipulacion = "No almacenar cerca de materiales combustibles y mantener el recipiente bien cerrado";
        this.prAuxInhalacion = "Transportar a la víctima al exterior y mantenerla en reposo en una posición confortable para respirar.";
        this.prAuxIngestion = "Hacer beber agua (maximo 2 vasos), evitar el vomito.";
        this.prAuxPiel = "Quitar inmediatamente todas las prendas contaminadas. Aclararse la piel con agua/ducharse.";
        this.prAuxOjos = "Enjuagar con agua cuidadosamente durante varios minutos. Quitar lentes de contacto cuando estén presentes y pueda hacerse con facilidad. Proseguir con el lavado.";
        this.prAuxOtras = "";
        this.peligroEspIncendio = "Favorece la formación de incendios por desprendimiento de oxigeno. El fuego puede provocar emanaciones de gases nitrosos y oxidos de nitrogeno.";
        this.peligroEspSalud = "Permanencia en el area de riesgo solo con sistemas de respiracion artificiales e independientes del ambiente.";
        this.recomendacionIncendio = "Reprimir los gases /vapores/neblinas con agua pulverizada. Enfriar los contenedores cerrados expuestos al fuego con agua pulverizada. Impedir la contaminación de las aguas superficiales o subterraneas por el agua que ha servido a la extinción del incendio.";
        this.agenteExtintor = "Polvo quimico seco. Dioxido de carbono.";
        this.ctrolProctecFuga = "Como acción inmediata de precaución inmediata, aisle en todas las direcciones el area del derrame como minimo 50 metros. No tirar los residuos por el desague.";
        this.ctrolLimpieza = "Recoger con materiales absorbentes de liquidos y neutralizante.";
        this.fichaSeguridad = "SI";
        this.tarjetaEmergencia = "SI";
        this.palabraEmergencia = "Peligro";
        this.imagen = "test.jpe";
    }
}