import { FrasesHModel } from './frasesh.model';
import { FrasesPModel } from './frasesp.model';
import { PeligrosidadNTCModel } from './peligrosidadNTC.model';
import { ProductoModel } from './producto.model';
import { SgaAmbientalModel } from './sgaambiental.model';
import { SgaFisicoModel } from './sgafisico.model';
import { SgaSaludModel } from './sgasalud.model';

export class RiesgoQuimicoModel{
    idRiesgo:number;
    idProductoFk: ProductoModel;
    idPeligrosidadNTC1692Fk:PeligrosidadNTCModel;
    gre:number;
    numeroUn:string;
    gas:string;
    cancerigeno:string;
    categoriaIARC:string;
    categoriaACGIH:string;
    nfpaS:number;
    nfpaI:number;
    nfpaR:number;
    nfpaE:string;
    idSGAFisicoFk:SgaFisicoModel;
    idSGAAmbientalFk:SgaAmbientalModel;
    idSGASaludFk:SgaSaludModel;
    reactividad:string;
    estabilidadQuimica:string;
    reaccionesPeligrosas:string;
    sustanciasIncompatibles:string;
    twa:string;
    stell:string;
    peligroInhalacion:string;
    peligroIngestion:string;
    peligroPiel:string;
    peligroOjos:string;
    efectosCronicos:string;
    medidasRespiratorias:string;
    medidasManos:string;
    medidasOjos:string;
    medidasPiel:string;
    medidasHigiene:string;
    medidasControlIng:string;
    medidasAlmacenamiento:string;
    medidasManipulacion:string;
    prAuxInhalacion:string;
    prAuxIngestion:string;
    prAuxPiel:string;
    prAuxOjos:string;
    prAuxOtras:string;
    peligroEspIncendio:string;
    peligroEspSalud:string;
    recomendacionIncendio:string;
    agenteExtintor:string;
    ctrolProctecFuga:string;
    ctrolLimpieza:string;
    fichaSeguridad:string;
    tarjetaEmergencia:string;
    palabraEmergencia:string;
    imagen:string;
    idFrasesPFk:FrasesPModel;
    idFrasesHFk:FrasesHModel;
    constructor(){
        this.idProductoFk = new ProductoModel;
        this.idPeligrosidadNTC1692Fk = new PeligrosidadNTCModel;
        this.idSGAFisicoFk = new SgaFisicoModel;
        this.idSGAAmbientalFk = new SgaAmbientalModel;
        this.idSGASaludFk  = new SgaSaludModel;
        this.idFrasesPFk = new FrasesPModel;
        this.idFrasesHFk = new FrasesHModel;
    }
}